apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sync
  #namespace: bagarote-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-sync
  template:
    metadata:
      labels:
        app: db-sync
    spec:
#      securityContext:
#        runAsUser: 5000
#        runAsGroup: 5000
      containers:
      - name: db-sync
        image: registry.bagarote.dev.br/bagarote/db-sync:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: APP_NAME
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: app_name
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: app_env
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: app_key
          - name: APP_DEBUG
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: app_debug
          - name: APP_URL
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: app_url
          - name: DB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: db_connection
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: db_host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: db_port
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: db_database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: db_password
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: pg_host
          - name: PGUSERNAME
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: pg_username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: pg_password
          - name: MAIL_MAILER
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_mailer
          - name: MAIL_HOST
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_host
          - name: MAIL_PORT
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_port
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_username
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_password
          - name: MAIL_FROM_ADDRESS
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_from_address
          - name: MAIL_FROM_NAME
            valueFrom:
              secretKeyRef:
                name: secrets-db-sync
                key: mail_from_name
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: NotIn
                values:
                - ks01
---
apiVersion: v1
kind: Service
metadata:
  name: db-sync-service
  #namespace: bagarote-prod
spec:
  selector:
    app: db-sync
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 80
